// 物語作成画面に必要な画像データ
var STORY_BACKGROUND;
var STORY_CHANGEMUSICBUTTON;
var STORY_PREVIEWFRAME;
var STORY_HUMAN_ILLUSTBUTTON_OFF;
var STORY_HUMAN_ILLUSTBUTTON_ON;
var STORY_ANIMAL_ILLUSTBUTTON_OFF;
var STORY_ANIMAL_ILLUSTBUTTON_ON;
var STORY_ITEM_ILLUSTBUTTON_OFF;
var STORY_ITEM_ILLUSTBUTTON_ON;
var STORY_BACKGROUND_ILLUSTBUTTON_OFF;
var STORY_BACKGROUND_ILLUSTBUTTON_ON;
var STORY_REMOVEBUTTON_OFF;
var STORY_REMOVEBUTTON_ON;
// 物語作成画面に必要な画像データ（明るさ-100)
var STORY_BACKGROUND_DARK;
var STORY_CHANGEMUSICBUTTON_DARK;
var STORY_HUMAN_ILLUSTBUTTON_OFF_DARK;
var STORY_HUMAN_ILLUSTBUTTON_ON_DARK;
var STORY_ANIMAL_ILLUSTBUTTON_OFF_DARK;
var STORY_ANIMAL_ILLUSTBUTTON_ON_DARK;
var STORY_ITEM_ILLUSTBUTTON_OFF_DARK;
var STORY_ITEM_ILLUSTBUTTON_ON_DARK;
var STORY_BACKGROUND_ILLUSTBUTTON_OFF_DARK;
var STORY_BACKGROUND_ILLUSTBUTTON_ON_DARK;
var STORY_REMOVEBUTTON_OFF_DARK;
var STORY_REMOVEBUTTON_ON_DARK;
// 物語の背景画像データ
var STORY_PREVIEWBACKGROUND_EMPTY;
var STORY_PREVIEWBACKGROUND_FOREST1;
var STORY_PREVIEWBACKGROUND_FOREST2;
var STORY_PREVIEWBACKGROUND_RIVER1;
var STORY_PREVIEWBACKGROUND_RIVER2;
var STORY_PREVIEWBACKGROUND_TOWN1;
var STORY_PREVIEWBACKGROUND_TOWN2;
var STORY_PREVIEWBACKGROUND_HOUSE1;
var STORY_PREVIEWBACKGROUND_HOUSE2;
// 物語の天気画像データ
var STORY_PREVIEWWEATHER_EMPTY;
var STORY_PREVIEWWEATHER_SUN;
var STORY_PREVIEWWEATHER_CLOUD;
var STORY_PREVIEWWEATHER_MOON;
// 物語に使用可能なオブジェクト画像データ
// 男性
var STORY_PREVIEWOBJECT_MAN_FRONT_GLAD;
var STORY_PREVIEWOBJECT_MAN_FRONT_ANGRY;
var STORY_PREVIEWOBJECT_MAN_FRONT_SAD;
var STORY_PREVIEWOBJECT_MAN_FRONT_ENJOY;
var STORY_PREVIEWOBJECT_MAN_RIGHT_GLAD;
var STORY_PREVIEWOBJECT_MAN_RIGHT_ANGRY;
var STORY_PREVIEWOBJECT_MAN_RIGHT_SAD;
var STORY_PREVIEWOBJECT_MAN_RIGHT_ENJOY;
var STORY_PREVIEWOBJECT_MAN_LEFT_GLAD;
var STORY_PREVIEWOBJECT_MAN_LEFT_ANGRY;
var STORY_PREVIEWOBJECT_MAN_LEFT_SAD;
var STORY_PREVIEWOBJECT_MAN_LEFT_ENJOY;
var STORY_PREVIEWOBJECT_MAN_BACK;
var STORY_PREVIEWOBJECT_MAN_FRONT_REMOVEFOCUS;
var STORY_PREVIEWOBJECT_MAN_BACK_REMOVEFOCUS;
var STORY_PREVIEWOBJECT_MAN_RIGHT_REMOVEFOCUS;
var STORY_PREVIEWOBJECT_MAN_LEFT_REMOVEFOCUS;
// 女性
var STORY_PREVIEWOBJECT_LADY_FRONT_GLAD;
var STORY_PREVIEWOBJECT_LADY_FRONT_ANGRY;
var STORY_PREVIEWOBJECT_LADY_FRONT_SAD;
var STORY_PREVIEWOBJECT_LADY_FRONT_ENJOY;
var STORY_PREVIEWOBJECT_LADY_RIGHT_GLAD;
var STORY_PREVIEWOBJECT_LADY_RIGHT_ANGRY;
var STORY_PREVIEWOBJECT_LADY_RIGHT_SAD;
var STORY_PREVIEWOBJECT_LADY_RIGHT_ENJOY;
var STORY_PREVIEWOBJECT_LADY_LEFT_GLAD;
var STORY_PREVIEWOBJECT_LADY_LEFT_ANGRY;
var STORY_PREVIEWOBJECT_LADY_LEFT_SAD;
var STORY_PREVIEWOBJECT_LADY_LEFT_ENJOY;
var STORY_PREVIEWOBJECT_LADY_BACK;
var STORY_PREVIEWOBJECT_LADY_FRONT_REMOVEFOCUS;
var STORY_PREVIEWOBJECT_LADY_BACK_REMOVEFOCUS;
var STORY_PREVIEWOBJECT_LADY_RIGHT_REMOVEFOCUS;
var STORY_PREVIEWOBJECT_LADY_LEFT_REMOVEFOCUS;
// 男の子
var STORY_PREVIEWOBJECT_BOY_FRONT_GLAD;
var STORY_PREVIEWOBJECT_BOY_FRONT_ANGRY;
var STORY_PREVIEWOBJECT_BOY_FRONT_SAD;
var STORY_PREVIEWOBJECT_BOY_FRONT_ENJOY;
var STORY_PREVIEWOBJECT_BOY_RIGHT_GLAD;
var STORY_PREVIEWOBJECT_BOY_RIGHT_ANGRY;
var STORY_PREVIEWOBJECT_BOY_RIGHT_SAD;
var STORY_PREVIEWOBJECT_BOY_RIGHT_ENJOY;
var STORY_PREVIEWOBJECT_BOY_LEFT_GLAD;
var STORY_PREVIEWOBJECT_BOY_LEFT_ANGRY;
var STORY_PREVIEWOBJECT_BOY_LEFT_SAD;
var STORY_PREVIEWOBJECT_BOY_LEFT_ENJOY;
var STORY_PREVIEWOBJECT_BOY_BACK;
var STORY_PREVIEWOBJECT_BOY_FRONT_REMOVEFOCUS;
var STORY_PREVIEWOBJECT_BOY_BACK_REMOVEFOCUS;
var STORY_PREVIEWOBJECT_BOY_RIGHT_REMOVEFOCUS;
var STORY_PREVIEWOBJECT_BOY_LEFT_REMOVEFOCUS;
// 女の子
var STORY_PREVIEWOBJECT_GIRL_FRONT_GLAD;
var STORY_PREVIEWOBJECT_GIRL_FRONT_ANGRY;
var STORY_PREVIEWOBJECT_GIRL_FRONT_SAD;
var STORY_PREVIEWOBJECT_GIRL_FRONT_ENJOY;
var STORY_PREVIEWOBJECT_GIRL_RIGHT_GLAD;
var STORY_PREVIEWOBJECT_GIRL_RIGHT_ANGRY;
var STORY_PREVIEWOBJECT_GIRL_RIGHT_SAD;
var STORY_PREVIEWOBJECT_GIRL_RIGHT_ENJOY;
var STORY_PREVIEWOBJECT_GIRL_LEFT_GLAD;
var STORY_PREVIEWOBJECT_GIRL_LEFT_ANGRY;
var STORY_PREVIEWOBJECT_GIRL_LEFT_SAD;
var STORY_PREVIEWOBJECT_GIRL_LEFT_ENJOY;
var STORY_PREVIEWOBJECT_GIRL_BACK;
var STORY_PREVIEWOBJECT_GIRL_FRONT_REMOVEFOCUS;
var STORY_PREVIEWOBJECT_GIRL_BACK_REMOVEFOCUS;
var STORY_PREVIEWOBJECT_GIRL_RIGHT_REMOVEFOCUS;
var STORY_PREVIEWOBJECT_GIRL_LEFT_REMOVEFOCUS;
// イヌ
var STORY_PREVIEWOBJECT_DOG_FRONT_GLAD;
var STORY_PREVIEWOBJECT_DOG_FRONT_ANGRY;
var STORY_PREVIEWOBJECT_DOG_FRONT_SAD;
var STORY_PREVIEWOBJECT_DOG_FRONT_ENJOY;
var STORY_PREVIEWOBJECT_DOG_RIGHT_GLAD;
var STORY_PREVIEWOBJECT_DOG_RIGHT_ANGRY;
var STORY_PREVIEWOBJECT_DOG_RIGHT_SAD;
var STORY_PREVIEWOBJECT_DOG_RIGHT_ENJOY;
var STORY_PREVIEWOBJECT_DOG_LEFT_GLAD;
var STORY_PREVIEWOBJECT_DOG_LEFT_ANGRY;
var STORY_PREVIEWOBJECT_DOG_LEFT_SAD;
var STORY_PREVIEWOBJECT_DOG_LEFT_ENJOY;
var STORY_PREVIEWOBJECT_DOG_BACK;
var STORY_PREVIEWOBJECT_DOG_FRONT_REMOVEFOCUS;
var STORY_PREVIEWOBJECT_DOG_BACK_REMOVEFOCUS;
var STORY_PREVIEWOBJECT_DOG_RIGHT_REMOVEFOCUS;
var STORY_PREVIEWOBJECT_DOG_LEFT_REMOVEFOCUS;
// トリ
var STORY_PREVIEWOBJECT_BIRD_FRONT_GLAD;
var STORY_PREVIEWOBJECT_BIRD_FRONT_ANGRY;
var STORY_PREVIEWOBJECT_BIRD_FRONT_SAD;
var STORY_PREVIEWOBJECT_BIRD_FRONT_ENJOY;
var STORY_PREVIEWOBJECT_BIRD_RIGHT_GLAD;
var STORY_PREVIEWOBJECT_BIRD_RIGHT_ANGRY;
var STORY_PREVIEWOBJECT_BIRD_RIGHT_SAD;
var STORY_PREVIEWOBJECT_BIRD_RIGHT_ENJOY;
var STORY_PREVIEWOBJECT_BIRD_LEFT_GLAD;
var STORY_PREVIEWOBJECT_BIRD_LEFT_ANGRY;
var STORY_PREVIEWOBJECT_BIRD_LEFT_SAD;
var STORY_PREVIEWOBJECT_BIRD_LEFT_ENJOY;
var STORY_PREVIEWOBJECT_BIRD_BACK;
var STORY_PREVIEWOBJECT_BIRD_FRONT_REMOVEFOCUS;
var STORY_PREVIEWOBJECT_BIRD_BACK_REMOVEFOCUS;
var STORY_PREVIEWOBJECT_BIRD_RIGHT_REMOVEFOCUS;
var STORY_PREVIEWOBJECT_BIRD_LEFT_REMOVEFOCUS;
// クマ
var STORY_PREVIEWOBJECT_BEAR_FRONT_GLAD;
var STORY_PREVIEWOBJECT_BEAR_FRONT_ANGRY;
var STORY_PREVIEWOBJECT_BEAR_FRONT_SAD;
var STORY_PREVIEWOBJECT_BEAR_FRONT_ENJOY;
var STORY_PREVIEWOBJECT_BEAR_RIGHT_GLAD;
var STORY_PREVIEWOBJECT_BEAR_RIGHT_ANGRY;
var STORY_PREVIEWOBJECT_BEAR_RIGHT_SAD;
var STORY_PREVIEWOBJECT_BEAR_RIGHT_ENJOY;
var STORY_PREVIEWOBJECT_BEAR_LEFT_GLAD;
var STORY_PREVIEWOBJECT_BEAR_LEFT_ANGRY;
var STORY_PREVIEWOBJECT_BEAR_LEFT_SAD;
var STORY_PREVIEWOBJECT_BEAR_LEFT_ENJOY;
var STORY_PREVIEWOBJECT_BEAR_BACK;
var STORY_PREVIEWOBJECT_BEAR_FRONT_REMOVEFOCUS;
var STORY_PREVIEWOBJECT_BEAR_BACK_REMOVEFOCUS;
var STORY_PREVIEWOBJECT_BEAR_RIGHT_REMOVEFOCUS;
var STORY_PREVIEWOBJECT_BEAR_LEFT_REMOVEFOCUS;
// カメ
var STORY_PREVIEWOBJECT_TURTLE_FRONT_GLAD;
var STORY_PREVIEWOBJECT_TURTLE_FRONT_ANGRY;
var STORY_PREVIEWOBJECT_TURTLE_FRONT_SAD;
var STORY_PREVIEWOBJECT_TURTLE_FRONT_ENJOY;
var STORY_PREVIEWOBJECT_TURTLE_RIGHT_GLAD;
var STORY_PREVIEWOBJECT_TURTLE_RIGHT_ANGRY;
var STORY_PREVIEWOBJECT_TURTLE_RIGHT_SAD;
var STORY_PREVIEWOBJECT_TURTLE_RIGHT_ENJOY;
var STORY_PREVIEWOBJECT_TURTLE_LEFT_GLAD;
var STORY_PREVIEWOBJECT_TURTLE_LEFT_ANGRY;
var STORY_PREVIEWOBJECT_TURTLE_LEFT_SAD;
var STORY_PREVIEWOBJECT_TURTLE_LEFT_ENJOY;
var STORY_PREVIEWOBJECT_TURTLE_BACK;
var STORY_PREVIEWOBJECT_TURTLE_FRONT_REMOVEFOCUS;
var STORY_PREVIEWOBJECT_TURTLE_BACK_REMOVEFOCUS;
var STORY_PREVIEWOBJECT_TURTLE_RIGHT_REMOVEFOCUS;
var STORY_PREVIEWOBJECT_TURTLE_LEFT_REMOVEFOCUS;
// パレットの画像
// パレット本体
var STORY_HUMANPALETTE;
var STORY_ANIMALPALETTE;
// とじるボタン
var STORY_PALETTECLOSEBUTTON;
// じんぶつ属性ボタン
var STORY_PALETTEPROPERTY_MAN_OFF;
var STORY_PALETTEPROPERTY_MAN_ON;
var STORY_PALETTEPROPERTY_LADY_OFF;
var STORY_PALETTEPROPERTY_LADY_ON;
var STORY_PALETTEPROPERTY_BOY_OFF;
var STORY_PALETTEPROPERTY_BOY_ON;
var STORY_PALETTEPROPERTY_GIRL_OFF;
var STORY_PALETTEPROPERTY_GIRL_ON;
// どうぶつ属性ボタン
var STORY_PALETTEPROPERTY_DOG_OFF;
var STORY_PALETTEPROPERTY_DOG_ON;
var STORY_PALETTEPROPERTY_BIRD_OFF;
var STORY_PALETTEPROPERTY_BIRD_ON;
var STORY_PALETTEPROPERTY_BEAR_OFF;
var STORY_PALETTEPROPERTY_BEAR_ON;
var STORY_PALETTEPROPERTY_TURTLE_OFF;
var STORY_PALETTEPROPERTY_TURTLE_ON;

var defineStoryImage = function() {
	// 物語作成画面に必要な画像データ
	STORY_BACKGROUND = new NormalImage("../image/story/appBackground.png", 1024, 768);
	STORY_CHANGEMUSICBUTTON = new NormalImage("../image/story/button/changeMusic.png", 100, 100);
	STORY_PREVIEWFRAME = new NormalImage("../image/story/preview/previewFrame.png", 690, 460);
	STORY_HUMAN_ILLUSTBUTTON_OFF = new NormalImage("../image/story/illustrations/humanButtonOff.png", 106, 73);
	STORY_HUMAN_ILLUSTBUTTON_ON = new NormalImage("../image/story/illustrations/humanButtonOn.png", 106, 73);
	STORY_ANIMAL_ILLUSTBUTTON_OFF = new NormalImage("../image/story/illustrations/animalButtonOff.png", 106, 73);
	STORY_ANIMAL_ILLUSTBUTTON_ON = new NormalImage("../image/story/illustrations/animalButtonOn.png", 106, 73);
	STORY_ITEM_ILLUSTBUTTON_OFF = new NormalImage("../image/story/illustrations/itemButtonOff.png", 106, 73);
	STORY_ITEM_ILLUSTBUTTON_ON = new NormalImage("../image/story/illustrations/itemButtonOn.png", 106, 73);
	STORY_BACKGROUND_ILLUSTBUTTON_OFF = new NormalImage("../image/story/illustrations/backgroundButtonOff.png", 106, 73);
	STORY_BACKGROUND_ILLUSTBUTTON_ON = new NormalImage("../image/story/illustrations/backgroundButtonOn.png", 106, 73);
	STORY_REMOVEBUTTON_OFF = new NormalImage("../image/story/preview/removeButtonOff.png", 106, 73);
	STORY_REMOVEBUTTON_ON = new NormalImage("../image/story/preview/removeButtonOn.png", 106, 73);
	// 物語作成画面に必要な画像データ(明るさ-100)
	STORY_BACKGROUND_DARK = new NormalImage("../image/story/appBackgroundDark.png", 1024, 768);
	STORY_CHANGEMUSICBUTTON_DARK = new NormalImage("../image/story/button/changeMusicDark.png", 100, 100);
	STORY_HUMAN_ILLUSTBUTTON_OFF_DARK = new NormalImage("../image/story/illustrations/humanButtonOffDark.png", 106, 73);
	STORY_HUMAN_ILLUSTBUTTON_ON_DARK = new NormalImage("../image/story/illustrations/humanButtonOnDark.png", 106, 73);
	STORY_ANIMAL_ILLUSTBUTTON_OFF_DARK = new NormalImage("../image/story/illustrations/animalButtonOffDark.png", 106, 73);
	STORY_ANIMAL_ILLUSTBUTTON_ON_DARK = new NormalImage("../image/story/illustrations/animalButtonOnDark.png", 106, 73);
	STORY_ITEM_ILLUSTBUTTON_OFF_DARK = new NormalImage("../image/story/illustrations/itemButtonOffDark.png", 106, 73);
	STORY_ITEM_ILLUSTBUTTON_ON_DARK = new NormalImage("../image/story/illustrations/itemButtonOnDark.png", 106, 73);
	STORY_BACKGROUND_ILLUSTBUTTON_OFF_DARK = new NormalImage("../image/story/illustrations/backgroundButtonOffDark.png", 106, 73);
	STORY_BACKGROUND_ILLUSTBUTTON_ON_DARK = new NormalImage("../image/story/illustrations/backgroundButtonOnDark.png", 106, 73);
	STORY_REMOVEBUTTON_OFF_DARK = new NormalImage("../image/story/preview/removeButtonOffDark.png", 106, 73);
	STORY_REMOVEBUTTON_ON_DARK = new NormalImage("../image/story/preview/removeButtonOnDark.png", 106, 73);
	// 物語の背景画像データ
	STORY_PREVIEWBACKGROUND_EMPTY = new NormalImage("../image/story/background/empty.png", 690, 460);
	STORY_PREVIEWBACKGROUND_FOREST1 = new NormalImage("../image/story/background/forest1.png", 690, 460);
	STORY_PREVIEWBACKGROUND_FOREST2 = new NormalImage("../image/story/background/forest2.png", 690, 460);
	STORY_PREVIEWBACKGROUND_RIVER1 = new NormalImage("../image/story/background/river1.png", 690, 460);
	STORY_PREVIEWBACKGROUND_RIVER2 = new NormalImage("../image/story/background/river2.png", 690, 460);
	STORY_PREVIEWBACKGROUND_TOWN1 = new NormalImage("../image/story/background/town1.png", 690, 460);
	STORY_PREVIEWBACKGROUND_TOWN2 = new NormalImage("../image/story/background/town2.png", 690, 460);
	STORY_PREVIEWBACKGROUND_HOUSE1 = new NormalImage("../image/story/background/house1.png", 690, 460);
	STORY_PREVIEWBACKGROUND_HOUSE2 = new NormalImage("../image/story/background/house2.png", 690, 460);
	// 物語の天気画像データ
	STORY_PREVIEWWEATHER_EMPTY = new NormalImage("../image/story/weather/empty.png", 690, 158);
	STORY_PREVIEWWEATHER_SUN = new NormalImage("../image/story/weather/sun.png", 690, 158);
	STORY_PREVIEWWEATHER_CLOUD = new NormalImage("../image/story/weather/cloud.png", 690, 158);
	STORY_PREVIEWWEATHER_MOON = new NormalImage("../image/story/weather/moon.png", 690, 158);
	// 物語に使用可能なオブジェクト画像データ
	// 男性
	STORY_PREVIEWOBJECT_MAN_FRONT_GLAD = new StoryPreviewImage("../image/story/human/man/front/glad.png", 48, 137, "human");
	STORY_PREVIEWOBJECT_MAN_FRONT_ANGRY = new StoryPreviewImage("../image/story/human/man/front/angry.png", 48, 137, "human");
	STORY_PREVIEWOBJECT_MAN_FRONT_SAD = new StoryPreviewImage("../image/story/human/man/front/sad.png", 48, 137, "human");
	STORY_PREVIEWOBJECT_MAN_FRONT_ENJOY = new StoryPreviewImage("../image/story/human/man/front/enjoy.png", 48, 137, "human");
	STORY_PREVIEWOBJECT_MAN_RIGHT_GLAD = new StoryPreviewImage("../image/story/human/man/right/glad.png", 38, 135, "human");
	STORY_PREVIEWOBJECT_MAN_RIGHT_ANGRY = new StoryPreviewImage("../image/story/human/man/right/angry.png", 38, 135, "human");
	STORY_PREVIEWOBJECT_MAN_RIGHT_SAD = new StoryPreviewImage("../image/story/human/man/right/sad.png", 38, 135, "human");
	STORY_PREVIEWOBJECT_MAN_RIGHT_ENJOY = new StoryPreviewImage("../image/story/human/man/right/enjoy.png", 38, 135, "human");
	STORY_PREVIEWOBJECT_MAN_LEFT_GLAD = new StoryPreviewImage("../image/story/human/man/left/glad.png", 36, 135, "human");
	STORY_PREVIEWOBJECT_MAN_LEFT_ANGRY = new StoryPreviewImage("../image/story/human/man/left/angry.png", 36, 135, "human");
	STORY_PREVIEWOBJECT_MAN_LEFT_SAD = new StoryPreviewImage("../image/story/human/man/left/sad.png", 36, 135, "human");
	STORY_PREVIEWOBJECT_MAN_LEFT_ENJOY = new StoryPreviewImage("../image/story/human/man/left/enjoy.png", 36, 135, "human");
	STORY_PREVIEWOBJECT_MAN_BACK = new StoryPreviewImage("../image/story/human/man/back/back.png", 46, 136, "human");
	STORY_PREVIEWOBJECT_MAN_FRONT_REMOVEFOCUS = new NormalImage("../image/story/human/man/front/manFrontRemoveFocus.png", 48, 137);
	STORY_PREVIEWOBJECT_MAN_BACK_REMOVEFOCUS = new NormalImage("../image/story/human/man/back/manBackRemoveFocus.png", 46, 136);
	STORY_PREVIEWOBJECT_MAN_RIGHT_REMOVEFOCUS = new NormalImage("../image/story/human/man/right/manRightRemoveFocus.png", 38, 135);
	STORY_PREVIEWOBJECT_MAN_LEFT_REMOVEFOCUS = new NormalImage("../image/story/human/man/left/manLeftRemoveFocus.png", 36, 135);
	// 女性
	STORY_PREVIEWOBJECT_LADY_FRONT_GLAD = new StoryPreviewImage("../image/story/human/lady/front/glad.png", 48, 125, "human");
	STORY_PREVIEWOBJECT_LADY_FRONT_ANGRY = new StoryPreviewImage("../image/story/human/lady/front/angry.png", 48, 125, "human");
	STORY_PREVIEWOBJECT_LADY_FRONT_SAD = new StoryPreviewImage("../image/story/human/lady/front/sad.png", 48, 125, "human");
	STORY_PREVIEWOBJECT_LADY_FRONT_ENJOY = new StoryPreviewImage("../image/story/human/lady/front/enjoy.png", 48, 125, "human");
	STORY_PREVIEWOBJECT_LADY_RIGHT_GLAD = new StoryPreviewImage("../image/story/human/lady/right/glad.png", 34, 127, "human");
	STORY_PREVIEWOBJECT_LADY_RIGHT_ANGRY = new StoryPreviewImage("../image/story/human/lady/right/angry.png", 34, 127, "human");
	STORY_PREVIEWOBJECT_LADY_RIGHT_SAD = new StoryPreviewImage("../image/story/human/lady/right/sad.png", 34, 127, "human");
	STORY_PREVIEWOBJECT_LADY_RIGHT_ENJOY = new StoryPreviewImage("../image/story/human/lady/right/enjoy.png", 34, 127, "human");
	STORY_PREVIEWOBJECT_LADY_LEFT_GLAD = new StoryPreviewImage("../image/story/human/lady/left/glad.png", 34, 127, "human");
	STORY_PREVIEWOBJECT_LADY_LEFT_ANGRY = new StoryPreviewImage("../image/story/human/lady/left/angry.png", 34, 127, "human");
	STORY_PREVIEWOBJECT_LADY_LEFT_SAD = new StoryPreviewImage("../image/story/human/lady/left/sad.png", 34, 127, "human");
	STORY_PREVIEWOBJECT_LADY_LEFT_ENJOY = new StoryPreviewImage("../image/story/human/lady/left/enjoy.png", 34, 127, "human");
	STORY_PREVIEWOBJECT_LADY_BACK = new StoryPreviewImage("../image/story/human/lady/back/back.png", 45, 124, "human");
	STORY_PREVIEWOBJECT_LADY_FRONT_REMOVEFOCUS = new NormalImage("../image/story/human/lady/front/ladyFrontRemoveFocus.png", 48, 125);
	STORY_PREVIEWOBJECT_LADY_BACK_REMOVEFOCUS = new NormalImage("../image/story/human/lady/back/ladyBackRemoveFocus.png", 45, 124);
	STORY_PREVIEWOBJECT_LADY_RIGHT_REMOVEFOCUS = new NormalImage("../image/story/human/lady/right/ladyRightRemoveFocus.png", 34, 127);
	STORY_PREVIEWOBJECT_LADY_LEFT_REMOVEFOCUS = new NormalImage("../image/story/human/lady/left/ladyLeftRemoveFocus.png", 34, 127);
	// 男の子
	STORY_PREVIEWOBJECT_BOY_FRONT_GLAD = new StoryPreviewImage("../image/story/human/boy/front/glad.png", 47, 109, "human");
	STORY_PREVIEWOBJECT_BOY_FRONT_ANGRY = new StoryPreviewImage("../image/story/human/boy/front/angry.png", 47, 109, "human");
	STORY_PREVIEWOBJECT_BOY_FRONT_SAD = new StoryPreviewImage("../image/story/human/boy/front/sad.png", 47, 109, "human");
	STORY_PREVIEWOBJECT_BOY_FRONT_ENJOY = new StoryPreviewImage("../image/story/human/boy/front/enjoy.png", 47, 109, "human");
	STORY_PREVIEWOBJECT_BOY_RIGHT_GLAD = new StoryPreviewImage("../image/story/human/boy/right/glad.png", 32, 109, "human");
	STORY_PREVIEWOBJECT_BOY_RIGHT_ANGRY = new StoryPreviewImage("../image/story/human/boy/right/angry.png", 32, 109, "human");
	STORY_PREVIEWOBJECT_BOY_RIGHT_SAD = new StoryPreviewImage("../image/story/human/boy/right/sad.png", 32, 109, "human");
	STORY_PREVIEWOBJECT_BOY_RIGHT_ENJOY = new StoryPreviewImage("../image/story/human/boy/right/enjoy.png", 32, 109, "human");
	STORY_PREVIEWOBJECT_BOY_LEFT_GLAD = new StoryPreviewImage("../image/story/human/boy/left/glad.png", 32, 109, "human");
	STORY_PREVIEWOBJECT_BOY_LEFT_ANGRY = new StoryPreviewImage("../image/story/human/boy/left/angry.png", 32, 109, "human");
	STORY_PREVIEWOBJECT_BOY_LEFT_SAD = new StoryPreviewImage("../image/story/human/boy/left/sad.png", 32, 109, "human");
	STORY_PREVIEWOBJECT_BOY_LEFT_ENJOY = new StoryPreviewImage("../image/story/human/boy/left/enjoy.png", 32, 109, "human");
	STORY_PREVIEWOBJECT_BOY_BACK = new StoryPreviewImage("../image/story/human/boy/back/back.png", 45, 109, "human");
	STORY_PREVIEWOBJECT_BOY_FRONT_REMOVEFOCUS = new NormalImage("../image/story/human/boy/front/boyFrontRemoveFocus.png", 47, 109);
	STORY_PREVIEWOBJECT_BOY_BACK_REMOVEFOCUS = new NormalImage("../image/story/human/boy/back/boyBackRemoveFocus.png", 45, 109);
	STORY_PREVIEWOBJECT_BOY_RIGHT_REMOVEFOCUS = new NormalImage("../image/story/human/boy/right/boyRightRemoveFocus.png", 32, 109);
	STORY_PREVIEWOBJECT_BOY_LEFT_REMOVEFOCUS = new NormalImage("../image/story/human/boy/left/boyLeftRemoveFocus.png", 32, 109);
	// 女の子
	STORY_PREVIEWOBJECT_GIRL_FRONT_GLAD = new StoryPreviewImage("../image/story/human/girl/front/glad.png", 50, 107, "human");
	STORY_PREVIEWOBJECT_GIRL_FRONT_ANGRY = new StoryPreviewImage("../image/story/human/girl/front/angry.png", 50, 107, "human");
	STORY_PREVIEWOBJECT_GIRL_FRONT_SAD = new StoryPreviewImage("../image/story/human/girl/front/sad.png", 50, 107, "human");
	STORY_PREVIEWOBJECT_GIRL_FRONT_ENJOY = new StoryPreviewImage("../image/story/human/girl/front/enjoy.png", 50, 107, "human");
	STORY_PREVIEWOBJECT_GIRL_RIGHT_GLAD = new StoryPreviewImage("../image/story/human/girl/right/glad.png", 44, 107, "human");
	STORY_PREVIEWOBJECT_GIRL_RIGHT_ANGRY = new StoryPreviewImage("../image/story/human/girl/right/angry.png", 44, 107, "human");
	STORY_PREVIEWOBJECT_GIRL_RIGHT_SAD = new StoryPreviewImage("../image/story/human/girl/right/sad.png", 44, 107, "human");
	STORY_PREVIEWOBJECT_GIRL_RIGHT_ENJOY = new StoryPreviewImage("../image/story/human/girl/right/enjoy.png", 44, 107, "human");
	STORY_PREVIEWOBJECT_GIRL_LEFT_GLAD = new StoryPreviewImage("../image/story/human/girl/left/glad.png", 43, 107, "human");
	STORY_PREVIEWOBJECT_GIRL_LEFT_ANGRY = new StoryPreviewImage("../image/story/human/girl/left/angry.png", 43, 107, "human");
	STORY_PREVIEWOBJECT_GIRL_LEFT_SAD = new StoryPreviewImage("../image/story/human/girl/left/sad.png", 43, 107, "human");
	STORY_PREVIEWOBJECT_GIRL_LEFT_ENJOY = new StoryPreviewImage("../image/story/human/girl/left/enjoy.png", 43, 107, "human");
	STORY_PREVIEWOBJECT_GIRL_BACK = new StoryPreviewImage("../image/story/human/girl/back/back.png", 51, 106, "human");
	STORY_PREVIEWOBJECT_GIRL_FRONT_REMOVEFOCUS = new NormalImage("../image/story/human/girl/front/girlFrontRemoveFocus.png", 50, 107);
	STORY_PREVIEWOBJECT_GIRL_BACK_REMOVEFOCUS = new NormalImage("../image/story/human/girl/back/girlBackRemoveFocus.png", 51, 106);
	STORY_PREVIEWOBJECT_GIRL_RIGHT_REMOVEFOCUS = new NormalImage("../image/story/human/girl/right/girlRightRemoveFocus.png", 44, 107);
	STORY_PREVIEWOBJECT_GIRL_LEFT_REMOVEFOCUS = new NormalImage("../image/story/human/girl/left/girlLeftRemoveFocus.png", 43, 107);
	// イヌ
	STORY_PREVIEWOBJECT_DOG_FRONT_GLAD = new StoryPreviewImage("../image/story/animal/dog/front/glad.png", 48, 73, "animal");
	STORY_PREVIEWOBJECT_DOG_FRONT_ANGRY = new StoryPreviewImage("../image/story/animal/dog/front/angry.png", 48, 73, "animal");
	STORY_PREVIEWOBJECT_DOG_FRONT_SAD = new StoryPreviewImage("../image/story/animal/dog/front/sad.png", 48, 73, "animal");
	STORY_PREVIEWOBJECT_DOG_FRONT_ENJOY = new StoryPreviewImage("../image/story/animal/dog/front/enjoy.png", 48, 73, "animal");
	STORY_PREVIEWOBJECT_DOG_RIGHT_GLAD = new StoryPreviewImage("../image/story/animal/dog/right/glad.png", 78, 75, "animal");
	STORY_PREVIEWOBJECT_DOG_RIGHT_ANGRY = new StoryPreviewImage("../image/story/animal/dog/right/angry.png", 78, 75, "animal");
	STORY_PREVIEWOBJECT_DOG_RIGHT_SAD = new StoryPreviewImage("../image/story/animal/dog/right/sad.png", 78, 75, "animal");
	STORY_PREVIEWOBJECT_DOG_RIGHT_ENJOY = new StoryPreviewImage("../image/story/animal/dog/right/enjoy.png", 78, 75, "animal");
	STORY_PREVIEWOBJECT_DOG_LEFT_GLAD = new StoryPreviewImage("../image/story/animal/dog/left/glad.png", 79, 75, "animal");
	STORY_PREVIEWOBJECT_DOG_LEFT_ANGRY = new StoryPreviewImage("../image/story/animal/dog/left/angry.png", 79, 75, "animal");
	STORY_PREVIEWOBJECT_DOG_LEFT_SAD = new StoryPreviewImage("../image/story/animal/dog/left/sad.png", 79, 75, "animal");
	STORY_PREVIEWOBJECT_DOG_LEFT_ENJOY = new StoryPreviewImage("../image/story/animal/dog/left/enjoy.png", 79, 75, "animal");
	STORY_PREVIEWOBJECT_DOG_BACK = new StoryPreviewImage("../image/story/animal/dog/back/back.png", 49, 76, "animal");
	STORY_PREVIEWOBJECT_DOG_FRONT_REMOVEFOCUS = new NormalImage("../image/story/animal/dog/front/dogFrontRemoveFocus.png", 46, 73);
	STORY_PREVIEWOBJECT_DOG_BACK_REMOVEFOCUS = new NormalImage("../image/story/animal/dog/back/dogBackRemoveFocus.png", 49, 76);
	STORY_PREVIEWOBJECT_DOG_RIGHT_REMOVEFOCUS = new NormalImage("../image/story/animal/dog/right/dogRightRemoveFocus.png", 78, 75);
	STORY_PREVIEWOBJECT_DOG_LEFT_REMOVEFOCUS = new NormalImage("../image/story/animal/dog/left/dogLeftRemoveFocus.png", 80, 75);
	// トリ
	STORY_PREVIEWOBJECT_BIRD_FRONT_GLAD = new StoryPreviewImage("../image/story/animal/bird/front/glad.png", 43, 48, "animal");
	STORY_PREVIEWOBJECT_BIRD_FRONT_ANGRY = new StoryPreviewImage("../image/story/animal/bird/front/angry.png", 43, 48, "animal");
	STORY_PREVIEWOBJECT_BIRD_FRONT_SAD = new StoryPreviewImage("../image/story/animal/bird/front/sad.png", 43, 48, "animal");
	STORY_PREVIEWOBJECT_BIRD_FRONT_ENJOY = new StoryPreviewImage("../image/story/animal/bird/front/enjoy.png", 43, 48, "animal");
	STORY_PREVIEWOBJECT_BIRD_RIGHT_GLAD = new StoryPreviewImage("../image/story/animal/bird/right/glad.png", 30, 44, "animal");
	STORY_PREVIEWOBJECT_BIRD_RIGHT_ANGRY = new StoryPreviewImage("../image/story/animal/bird/right/angry.png", 30, 44, "animal");
	STORY_PREVIEWOBJECT_BIRD_RIGHT_SAD = new StoryPreviewImage("../image/story/animal/bird/right/sad.png", 30, 44, "animal");
	STORY_PREVIEWOBJECT_BIRD_RIGHT_ENJOY = new StoryPreviewImage("../image/story/animal/bird/right/enjoy.png", 30, 44, "animal");
	STORY_PREVIEWOBJECT_BIRD_LEFT_GLAD = new StoryPreviewImage("../image/story/animal/bird/left/glad.png", 32, 44, "animal");
	STORY_PREVIEWOBJECT_BIRD_LEFT_ANGRY = new StoryPreviewImage("../image/story/animal/bird/left/angry.png", 32, 44, "animal");
	STORY_PREVIEWOBJECT_BIRD_LEFT_SAD = new StoryPreviewImage("../image/story/animal/bird/left/sad.png", 32, 44, "animal");
	STORY_PREVIEWOBJECT_BIRD_LEFT_ENJOY = new StoryPreviewImage("../image/story/animal/bird/left/enjoy.png", 32, 44, "animal");
	STORY_PREVIEWOBJECT_BIRD_BACK = new StoryPreviewImage("../image/story/animal/bird/back/back.png", 44, 46, "animal");
	STORY_PREVIEWOBJECT_BIRD_FRONT_REMOVEFOCUS = new NormalImage("../image/story/animal/bird/front/birdFrontRemoveFocus.png", 43, 48);
	STORY_PREVIEWOBJECT_BIRD_BACK_REMOVEFOCUS = new NormalImage("../image/story/animal/bird/back/birdBackRemoveFocus.png", 44, 46);
	STORY_PREVIEWOBJECT_BIRD_RIGHT_REMOVEFOCUS = new NormalImage("../image/story/animal/bird/right/birdRightRemoveFocus.png", 30, 44);
	STORY_PREVIEWOBJECT_BIRD_LEFT_REMOVEFOCUS = new NormalImage("../image/story/animal/bird/left/birdLeftRemoveFocus.png", 32, 44);
	// クマ
	STORY_PREVIEWOBJECT_BEAR_FRONT_GLAD = new StoryPreviewImage("../image/story/animal/bear/front/glad.png", 52, 107, "animal");
	STORY_PREVIEWOBJECT_BEAR_FRONT_ANGRY = new StoryPreviewImage("../image/story/animal/bear/front/angry.png", 52, 107, "animal");
	STORY_PREVIEWOBJECT_BEAR_FRONT_SAD = new StoryPreviewImage("../image/story/animal/bear/front/sad.png", 52, 107, "animal");
	STORY_PREVIEWOBJECT_BEAR_FRONT_ENJOY = new StoryPreviewImage("../image/story/animal/bear/front/enjoy.png", 52, 107, "animal");
	STORY_PREVIEWOBJECT_BEAR_RIGHT_GLAD = new StoryPreviewImage("../image/story/animal/bear/right/glad.png", 39, 107, "animal");
	STORY_PREVIEWOBJECT_BEAR_RIGHT_ANGRY = new StoryPreviewImage("../image/story/animal/bear/right/angry.png", 39, 107, "animal");
	STORY_PREVIEWOBJECT_BEAR_RIGHT_SAD = new StoryPreviewImage("../image/story/animal/bear/right/sad.png", 39, 107, "animal");
	STORY_PREVIEWOBJECT_BEAR_RIGHT_ENJOY = new StoryPreviewImage("../image/story/animal/bear/right/enjoy.png", 39, 107, "animal");
	STORY_PREVIEWOBJECT_BEAR_LEFT_GLAD = new StoryPreviewImage("../image/story/animal/bear/left/glad.png", 39, 107, "animal");
	STORY_PREVIEWOBJECT_BEAR_LEFT_ANGRY = new StoryPreviewImage("../image/story/animal/bear/left/angry.png", 39, 107, "animal");
	STORY_PREVIEWOBJECT_BEAR_LEFT_SAD = new StoryPreviewImage("../image/story/animal/bear/left/sad.png", 39, 107, "animal");
	STORY_PREVIEWOBJECT_BEAR_LEFT_ENJOY = new StoryPreviewImage("../image/story/animal/bear/left/enjoy.png", 39, 107, "animal");
	STORY_PREVIEWOBJECT_BEAR_BACK = new StoryPreviewImage("../image/story/animal/bear/back/back.png", 49, 106, "animal");
	STORY_PREVIEWOBJECT_BEAR_FRONT_REMOVEFOCUS = new NormalImage("../image/story/animal/bear/front/bearFrontRemoveFocus.png", 52, 107);
	STORY_PREVIEWOBJECT_BEAR_BACK_REMOVEFOCUS = new NormalImage("../image/story/animal/bear/back/bearBackRemoveFocus.png", 49, 106);
	STORY_PREVIEWOBJECT_BEAR_RIGHT_REMOVEFOCUS = new NormalImage("../image/story/animal/bear/right/bearRightRemoveFocus.png", 39, 107);
	STORY_PREVIEWOBJECT_BEAR_LEFT_REMOVEFOCUS = new NormalImage("../image/story/animal/bear/left/bearLeftRemoveFocus.png", 39, 107);
	// カメ
	STORY_PREVIEWOBJECT_TURTLE_FRONT_GLAD = new StoryPreviewImage("../image/story/animal/turtle/front/glad.png", 56, 49, "animal");
	STORY_PREVIEWOBJECT_TURTLE_FRONT_ANGRY = new StoryPreviewImage("../image/story/animal/turtle/front/angry.png", 56, 49, "animal");
	STORY_PREVIEWOBJECT_TURTLE_FRONT_SAD = new StoryPreviewImage("../image/story/animal/turtle/front/sad.png", 56, 49, "animal");
	STORY_PREVIEWOBJECT_TURTLE_FRONT_ENJOY = new StoryPreviewImage("../image/story/animal/turtle/front/enjoy.png", 56, 49, "animal");
	STORY_PREVIEWOBJECT_TURTLE_RIGHT_GLAD = new StoryPreviewImage("../image/story/animal/turtle/right/glad.png", 74, 41, "animal");
	STORY_PREVIEWOBJECT_TURTLE_RIGHT_ANGRY = new StoryPreviewImage("../image/story/animal/turtle/right/angry.png", 74, 41, "animal");
	STORY_PREVIEWOBJECT_TURTLE_RIGHT_SAD = new StoryPreviewImage("../image/story/animal/turtle/right/sad.png", 74, 41, "animal");
	STORY_PREVIEWOBJECT_TURTLE_RIGHT_ENJOY = new StoryPreviewImage("../image/story/animal/turtle/right/enjoy.png", 74, 41, "animal");
	STORY_PREVIEWOBJECT_TURTLE_LEFT_GLAD = new StoryPreviewImage("../image/story/animal/turtle/left/glad.png", 75, 41, "animal");
	STORY_PREVIEWOBJECT_TURTLE_LEFT_ANGRY = new StoryPreviewImage("../image/story/animal/turtle/left/angry.png", 75, 41, "animal");
	STORY_PREVIEWOBJECT_TURTLE_LEFT_SAD = new StoryPreviewImage("../image/story/animal/turtle/left/sad.png", 75, 41, "animal");
	STORY_PREVIEWOBJECT_TURTLE_LEFT_ENJOY = new StoryPreviewImage("../image/story/animal/turtle/left/enjoy.png", 75, 41, "animal");
	STORY_PREVIEWOBJECT_TURTLE_BACK = new StoryPreviewImage("../image/story/animal/turtle/back/back.png", 53, 48, "animal");
	STORY_PREVIEWOBJECT_TURTLE_FRONT_REMOVEFOCUS = new NormalImage("../image/story/animal/turtle/front/turtleFrontRemoveFocus.png", 56, 49);
	STORY_PREVIEWOBJECT_TURTLE_BACK_REMOVEFOCUS = new NormalImage("../image/story/animal/turtle/back/turtleBackRemoveFocus.png", 53, 48);
	STORY_PREVIEWOBJECT_TURTLE_RIGHT_REMOVEFOCUS = new NormalImage("../image/story/animal/turtle/right/turtleRightRemoveFocus.png", 74, 41);
	STORY_PREVIEWOBJECT_TURTLE_LEFT_REMOVEFOCUS = new NormalImage("../image/story/animal/turtle/left/turtleLeftRemoveFocus.png", 75, 41);
	// パレットの画像
	// パレット
	STORY_HUMANPALETTE = new NormalImage("../image/story/palette/humanPalette.png", 800, 600);
	STORY_ANIMALPALETTE = new NormalImage("../image/story/palette/animalPalette.png", 1000, 600);
	// とじるボタン
	STORY_PALETTECLOSEBUTTON = new NormalImage("../image/story/palette/close.png", 83, 44);
	// じんぶつ属性ボタン
	STORY_PALETTEPROPERTY_MAN_OFF = new NormalImage("../image/story/palette/property/man/manOff.png", 87, 77);
	STORY_PALETTEPROPERTY_MAN_ON = new NormalImage("../image/story/palette/property/man/manOn.png", 87, 77);
	STORY_PALETTEPROPERTY_LADY_OFF = new NormalImage("../image/story/palette/property/lady/ladyOff.png", 87, 77);
	STORY_PALETTEPROPERTY_LADY_ON = new NormalImage("../image/story/palette/property/lady/ladyOn.png", 87, 77);
	STORY_PALETTEPROPERTY_BOY_OFF = new NormalImage("../image/story/palette/property/boy/boyOff.png", 87, 77);
	STORY_PALETTEPROPERTY_BOY_ON = new NormalImage("../image/story/palette/property/boy/boyOn.png", 87, 77);
	STORY_PALETTEPROPERTY_GIRL_OFF = new NormalImage("../image/story/palette/property/girl/girlOff.png", 87, 77);
	STORY_PALETTEPROPERTY_GIRL_ON = new NormalImage("../image/story/palette/property/girl/girlOn.png", 87, 77);
	// どうぶつ属性ボタン
	STORY_PALETTEPROPERTY_DOG_OFF = new NormalImage("../image/story/palette/property/dog/dogOff.png", 87, 77);
	STORY_PALETTEPROPERTY_DOG_ON = new NormalImage("../image/story/palette/property/dog/dogOn.png", 87, 77);
	STORY_PALETTEPROPERTY_BIRD_OFF = new NormalImage("../image/story/palette/property/bird/birdOff.png", 87, 77);
	STORY_PALETTEPROPERTY_BIRD_ON = new NormalImage("../image/story/palette/property/bird/birdOn.png", 87, 77);
	STORY_PALETTEPROPERTY_BEAR_OFF = new NormalImage("../image/story/palette/property/bear/bearOff.png", 87, 77);
	STORY_PALETTEPROPERTY_BEAR_ON = new NormalImage("../image/story/palette/property/bear/bearOn.png", 87, 77);
	STORY_PALETTEPROPERTY_TURTLE_OFF = new NormalImage("../image/story/palette/property/turtle/turtleOff.png", 87, 77);
	STORY_PALETTEPROPERTY_TURTLE_ON = new NormalImage("../image/story/palette/property/turtle/turtleOn.png", 87, 77);
}