var preloadMusicImage = function() {
	// 作曲画面の画像のプリロード
	core.preload(MUSIC_BACKGROUND._path);
	core.preload(MUSIC_CHANGESTORYBUTTON_OFF._path);
	core.preload(MUSIC_CHANGESTORYBUTTON_ON._path);
	core.preload(MUSIC_SAVEBUTTON_OFF._path);
	core.preload(MUSIC_SAVEBUTTON_ON._path);
	core.preload(MUSIC_LOADBUTTON_OFF._path);
	core.preload(MUSIC_LOADBUTTON_ON._path);
	core.preload(MUSIC_HUMEN._path);
	core.preload(MUSIC_MEASUREBOARD._path);
	core.preload(MUSIC_PLAYBUTTON_OFF._path);
	core.preload(MUSIC_PLAYBUTTON_ON._path);
	core.preload(MUSIC_NEXTBUTTON_OFF._path);
	core.preload(MUSIC_NEXTBUTTON_ON._path);
	core.preload(MUSIC_PREVBUTTON_OFF._path);
	core.preload(MUSIC_PREVBUTTON_ON._path);
	core.preload(MUSIC_PIANOBUTTON_OFF._path);
	core.preload(MUSIC_PIANOBUTTON_ON._path);
	core.preload(MUSIC_PIANOBUTTON_PUSH._path);
	core.preload(MUSIC_REMOVEBUTTON_OFF._path);
	core.preload(MUSIC_REMOVEBUTTON_ON._path);
	core.preload(MUSIC_REMOVEBUTTON_PUSH._path);
	core.preload(MUSIC_REMOVEFOCUS_LIGHT._path);
	core.preload(MUSIC_REMOVEFOCUS_DEEP._path);
	core.preload(MUSIC_INTRO_DIALOG._path);
	core.preload(MUSIC_YESBUTTON_OFF._path);
	core.preload(MUSIC_YESBUTTON_ON._path);
	core.preload(MUSIC_ANIMAL["cat"]._path);

	core.preload(MUSIC_BACKGROUND_DARK._path);
	core.preload(MUSIC_CHANGESTORYBUTTON_DARK._path);
	core.preload(MUSIC_SAVEBUTTON_DARK._path);
	core.preload(MUSIC_LOADBUTTON_DARK._path);
	core.preload(MUSIC_HUMEN_DARK._path);
	core.preload(MUSIC_MEASUREBOARD_DARK._path);
	core.preload(MUSIC_PLAYBUTTON_DARK._path);
	core.preload(MUSIC_NEXTBUTTON_DARK._path);
	core.preload(MUSIC_PREVBUTTON_DARK._path);
	core.preload(MUSIC_PIANOBUTTON_DARK._path);
	core.preload(MUSIC_REMOVEBUTTON_DARK._path);
}